---
- name: Disable swap
  command: swapoff -a

- name: Load kernel modules
  blockinfile:
    path: /etc/modules-load.d/k8s.conf
    block: |
      overlay
      br_netfilter

- name: Load kernel modules immediately
  shell: modprobe overlay && modprobe br_netfilter

- name: Configure system parameters
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Apply sysctl settings
  command: sysctl --system

- name: Configure containerd
  command: containerd config default | tee /etc/containerd/config.toml

- name: Update containerd config
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted

- name: Check containerd status
  systemd:
    name: containerd
    state: status
  ignore_errors: yes

